from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, Any, List, Optional

@dataclass
class FactorCandidate:
    """
    Standard factor candidate object generated by any MiningEngine.
    """
    factor_id: str
    expression: str
    engine: str
    engine_version: str = "unknown"
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    search_space_id: Optional[str] = None
    parent_ids: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    # Fields added for modular platform alignment
    raw_expression: Optional[str] = None
    canonical_expr: Optional[str] = None
    source_run_id: Optional[str] = None

    def __post_init__(self):
        if not self.factor_id:
            # Generate a simple hash-based ID if not provided
            import hashlib
            payload = f"{self.expression}|{self.engine}|{self.search_space_id}"
            self.factor_id = hashlib.sha256(payload.encode()).hexdigest()[:16]
